### ISSUE TITLE
ParserUtil violates DRY principle

### ISSUE THREAD

**Issue by Jefferson111** [AY1920S1-CS2113T-W13-3/main#147]
I notice that some of the methods are essentially trying to do the same thing.
Sort out the fields/indexes required and use a cleaner method to extract them.
e.g.
```getFirstIndex(userInput)```
Means I will get the first number in the string: 
```Command 122 blah 233 dah```
```Command nndd 122 ddd 444 kkk```
```Command ddd fff 122 333```
Expect output for all: ```122```

**Comment by Inno97** [comment]
Fixed in upcoming PR.

Universal methods implemented:
 - getFieldInList(int index, int listSize, String userInput)
 - getIntegerInList(int index, int listSize, String userInput)
 - getIntegerIndexInList(int index, int listSize, String userInput)

Splits a String input, giving a maximum array size of listSize and fetches the content at the specified index.

getIntegerInList and getIntegerIndexInList will cast to int and throw InputNotIntException if it fails.
getIntegerIndexInList will automatically decrement the output.
