### ISSUE TITLE
Find path command has bugs

### ISSUE THREAD

**Issue by Jefferson111** [AY1920S1-CS2113T-W13-3/main#148]
Try adding a lot of locations and findPath between the locations. I was using the west area locations when discovering the bug; jCube, Tuas, River valley high school, etc.

However, the onlyBus constraints is working fine.

**Comment by Inno97** [comment]
I've added some fixes to the underlying code at PathFinder (which FindPathCommand uses) in my latest build. This was because I am making a RouteGenerateCommand, which automatically generates a Route based on 2 queried locations.

I will be making the PR soon, as soon as I create the necessary conversations for the RouteGenerateCommand. From a few tests that I have made, it seems that the path finding is corrected in my current build. 

Once that PR is merged, please check and try out the FindPathCommand and RouteGenerateCommand. Though I will not be fully certain whether the FindPathCommand will necessarily work correctly, since I did not touch the command at all.

**Comment by Jefferson111** [comment]
👍
